/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShadersRouteImport } from './routes/shaders'
import { Route as SeedMapRouteImport } from './routes/seed-map'
import { Route as ResourcePacksRouteImport } from './routes/resource-packs'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as ModsRouteImport } from './routes/mods'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as DatapacksRouteImport } from './routes/datapacks'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItemsIdRouteImport } from './routes/items.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadersRoute = ShadersRouteImport.update({
  id: '/shaders',
  path: '/shaders',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedMapRoute = SeedMapRouteImport.update({
  id: '/seed-map',
  path: '/seed-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcePacksRoute = ResourcePacksRouteImport.update({
  id: '/resource-packs',
  path: '/resource-packs',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const ModsRoute = ModsRouteImport.update({
  id: '/mods',
  path: '/mods',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const DatapacksRoute = DatapacksRouteImport.update({
  id: '/datapacks',
  path: '/datapacks',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIdRoute = ItemsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ItemsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/datapacks': typeof DatapacksRoute
  '/items': typeof ItemsRouteWithChildren
  '/mods': typeof ModsRoute
  '/players': typeof PlayersRoute
  '/plugins': typeof PluginsRoute
  '/resource-packs': typeof ResourcePacksRoute
  '/seed-map': typeof SeedMapRoute
  '/shaders': typeof ShadersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/items/$id': typeof ItemsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/datapacks': typeof DatapacksRoute
  '/items': typeof ItemsRouteWithChildren
  '/mods': typeof ModsRoute
  '/players': typeof PlayersRoute
  '/plugins': typeof PluginsRoute
  '/resource-packs': typeof ResourcePacksRoute
  '/seed-map': typeof SeedMapRoute
  '/shaders': typeof ShadersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/items/$id': typeof ItemsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/datapacks': typeof DatapacksRoute
  '/items': typeof ItemsRouteWithChildren
  '/mods': typeof ModsRoute
  '/players': typeof PlayersRoute
  '/plugins': typeof PluginsRoute
  '/resource-packs': typeof ResourcePacksRoute
  '/seed-map': typeof SeedMapRoute
  '/shaders': typeof ShadersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/items/$id': typeof ItemsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/datapacks'
    | '/items'
    | '/mods'
    | '/players'
    | '/plugins'
    | '/resource-packs'
    | '/seed-map'
    | '/shaders'
    | '/sitemap.xml'
    | '/items/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/datapacks'
    | '/items'
    | '/mods'
    | '/players'
    | '/plugins'
    | '/resource-packs'
    | '/seed-map'
    | '/shaders'
    | '/sitemap.xml'
    | '/items/$id'
  id:
    | '__root__'
    | '/'
    | '/clients'
    | '/datapacks'
    | '/items'
    | '/mods'
    | '/players'
    | '/plugins'
    | '/resource-packs'
    | '/seed-map'
    | '/shaders'
    | '/sitemap.xml'
    | '/items/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsRoute: typeof ClientsRoute
  DatapacksRoute: typeof DatapacksRoute
  ItemsRoute: typeof ItemsRouteWithChildren
  ModsRoute: typeof ModsRoute
  PlayersRoute: typeof PlayersRoute
  PluginsRoute: typeof PluginsRoute
  ResourcePacksRoute: typeof ResourcePacksRoute
  SeedMapRoute: typeof SeedMapRoute
  ShadersRoute: typeof ShadersRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shaders': {
      id: '/shaders'
      path: '/shaders'
      fullPath: '/shaders'
      preLoaderRoute: typeof ShadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seed-map': {
      id: '/seed-map'
      path: '/seed-map'
      fullPath: '/seed-map'
      preLoaderRoute: typeof SeedMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource-packs': {
      id: '/resource-packs'
      path: '/resource-packs'
      fullPath: '/resource-packs'
      preLoaderRoute: typeof ResourcePacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mods': {
      id: '/mods'
      path: '/mods'
      fullPath: '/mods'
      preLoaderRoute: typeof ModsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datapacks': {
      id: '/datapacks'
      path: '/datapacks'
      fullPath: '/datapacks'
      preLoaderRoute: typeof DatapacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$id': {
      id: '/items/$id'
      path: '/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof ItemsIdRouteImport
      parentRoute: typeof ItemsRoute
    }
  }
}

interface ItemsRouteChildren {
  ItemsIdRoute: typeof ItemsIdRoute
}

const ItemsRouteChildren: ItemsRouteChildren = {
  ItemsIdRoute: ItemsIdRoute,
}

const ItemsRouteWithChildren = ItemsRoute._addFileChildren(ItemsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsRoute: ClientsRoute,
  DatapacksRoute: DatapacksRoute,
  ItemsRoute: ItemsRouteWithChildren,
  ModsRoute: ModsRoute,
  PlayersRoute: PlayersRoute,
  PluginsRoute: PluginsRoute,
  ResourcePacksRoute: ResourcePacksRoute,
  SeedMapRoute: SeedMapRoute,
  ShadersRoute: ShadersRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
